### ISSUE TITLE
What is this code doing?

### ISSUE THREAD

**Issue by acbart** [UD-CISC275-F21/ud-cis-scheduler-team-18#15]
https://github.com/UD-CISC275-F21/ud-cis-scheduler-team-18/blob/80c984c65ca26ba1d394d4e22cea317a4d0db6db/src/components/ClassListViewer.tsx#L9-L13

**Comment by mccrackudel** [comment]
Checked the CARDS as Card[]; line, is not necessary and is now commented out. The rest of the code creates a string of courses from the json to display as courses required.
